version: '3.8'

services:
    # PHP & Laravel Service
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: my-todo-app-laravel
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        networks:
            - app-network

    # Nginx Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app-network

    # MySQL Service
    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ToDoApp
            MYSQL_USER: user
            MYSQL_PASSWORD: passowrd
            MYSQL_ROOT_PASSWORD: passowrd
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

    # Node Service for Vite & React
    node:
        image: node:18-alpine
        container_name: node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "3000:3000"
        environment:
            SERVICE_TAGS: dev
        networks:
            - app-network
        command: sh -c "npm install && npm run dev"

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
